### ISSUE TITLE
argo-ui fails to build docker image

### ISSUE THREAD

**Issue by wookasz** [argoproj/argo-ui#2]
**Is this a feature request of a bug?**
Bug

**What happened**
Running:
```
docker build .
```

results in the following error:

```
$ webpack --config ./src/app/webpack.config.js
/src/node_modules/webpack/bin/webpack.js:348
			throw err;
			^

SyntaxError: Error parsing /src/node_modules/node-libs-browser/package.json: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at readPackage (module.js:133:52)
    at tryPackage (module.js:143:13)
    at Function.Module._findPath (module.js:225:20)
    at Function.Module._resolveFilename (module.js:553:25)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/node_modules/webpack/lib/node/NodeSourcePlugin.js:8:25)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at WebpackOptionsApply.process (/src/node_modules/webpack/lib/WebpackOptionsApply.js:71:25)
    at webpack (/src/node_modules/webpack/lib/webpack.js:37:48)
    at processOptions (/src/node_modules/webpack/bin/webpack.js:335:15)
    at yargs.parse (/src/node_modules/webpack/bin/webpack.js:396:2)
    at Object.Yargs.self.parse (/src/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/src/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:193:16)
    at bootstrap_node.js:617:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c NODE_ENV='production' yarn build && yarn cache clean && yarn install --production' returned a non-zero code: 1
```

**What you expect to happen**
The image should build successfully

**Details**
I'm using latest `master` https://github.com/argoproj/argo-ui/commit/b0676cd9d1a04709a33bd18fd2d40a8b911649c2

The problem is an extra newline character at the end of `package.json`

**Comment by alexmt** [comment]
Hello @wookasz ,

I suspect this is caused by this docker bug: https://github.com/docker/for-mac/issues/2625 .  I've encountered the same issue before.  Build run successfully after I run `docker system prune` but later I've got the similar error again. The problem went away completely after I've upgraded to most recent docker version and reset docker to factory defaults (from the Whale menu -> Preferences -> Reset).

Can you please try running `docker system prune` and build again? I hope I'm not missing something obvious.

Thanks,
Alex

**Comment by wookasz** [comment]
`docker system prune` seems to have done the trick. Thanks.
